### ISSUE TITLE
Re-exporting fred

### ISSUE THREAD

**Issue by Ken-Miura** [brkp/async-fred-session#2]
When I use this crate, I have to add and manage two dependencies (this crate and fred). If this crate re-exports fred, developer can use this crate by adding just this crate dependency (without adding and managing fred dependency). So I think it s better to re-export fred. What do you think?

**Comment by seg6** [comment]
@Ken-Miura Hey! Thanks for bringing this up, I also think that it does make sense to re-export `fred`.

If you'd like to, you can go ahead and submit a patch for this and I'll merge, otherwise I'm not immediately available to do the change.

**Comment by Ken-Miura** [comment]
@brkp Thank you for reply. I created PR. Could you check it?
