### ISSUE TITLE
Bump fred to 6.3.0

### ISSUE THREAD

**Issue by Elizafox** [brkp/async-fred-session#4]
Hello,

fred should be bumped to the latest version :).

**Comment by seg6** [comment]
Hey, thanks for reaching out. I thought I already had dependabot set up properly, but it seems that's not the case. I'll fix things up as soon as possible.

**Comment by seg6** [comment]
Resolved here: [v0.1.5](https://crates.io/crates/async-fred-session/0.1.5).
